/**
 * Snapshot the Android section of the resolved ExpoConfig so any
 * regression that re-introduces a privacy-sensitive permission or
 * silently mangles the Health Connect intent filter is caught at CI
 * time, BEFORE someone burns an EAS build slot.
 *
 * The manifest itself is generated by `expo prebuild` (which runs
 * gradle's manifest merger), but most of the offenders live one layer
 * earlier — in the JS config object that the prebuild transforms.
 * Pinning the JS config catches:
 *   - someone adds back the broken manual `intentFilters` for the
 *     Health Connect rationale (Expo's normalizer mangles the action
 *     name)
 *   - someone disables the local hardening plugin
 *   - someone removes the `react-native-health-connect` plugin and
 *     the Health Connect consent flow silently breaks
 *   - someone re-enables `recordAudioAndroid` / `microphonePermission`
 *     on expo-camera or expo-image-picker, putting RECORD_AUDIO back
 *     into the manifest
 *   - someone hard-codes a versionCode and breaks the EAS auto-bump
 */

// expo/config evaluates app.config.ts in a Node context. We need the
// Node-style env to be empty so resolveVersionCode returns the default 1.
const ORIGINAL_ENV = { ...process.env };

afterEach(() => {
  process.env = { ...ORIGINAL_ENV };
});

type AppConfigFactory = (ctx: { config: Record<string, unknown> }) => {
  android?: {
    package?: string;
    versionCode?: number;
    permissions?: string[];
    intentFilters?: { action?: string; category?: string[] }[];
    softwareKeyboardLayoutMode?: string;
  };
  plugins?: (string | [string, Record<string, unknown>])[];
};

function loadConfig() {
  // `jest.isolateModules` runs the require in a sandboxed module
  // registry so each call re-evaluates `app.config.ts` from scratch
  // and re-reads `process.env`.
  let result: ReturnType<AppConfigFactory> | undefined;
  jest.isolateModules(() => {
    const mod = require("../../app.config.ts").default as AppConfigFactory;
    result = mod({ config: {} });
  });
  if (!result) throw new Error("loadConfig: factory returned nothing");
  return result;
}

describe("app.config.ts (Android)", () => {
  it("declares the exact set of runtime permissions we actually need", () => {
    const config = loadConfig();
    const perms = config.android?.permissions ?? [];
    expect(perms).toEqual(
      expect.arrayContaining([
        "android.permission.INTERNET",
        "android.permission.ACCESS_NETWORK_STATE",
        "android.permission.CAMERA",
        "android.permission.READ_MEDIA_IMAGES",
        "android.permission.POST_NOTIFICATIONS",
        "android.permission.USE_BIOMETRIC",
        "android.permission.USE_FINGERPRINT",
        "android.permission.VIBRATE",
        "android.permission.health.READ_STEPS",
        "android.permission.health.READ_HEART_RATE",
        "android.permission.health.READ_SLEEP",
        "android.permission.health.READ_WEIGHT",
      ])
    );
    // Hard-blocked (would land in the manifest by accident otherwise).
    expect(perms).not.toContain("android.permission.RECORD_AUDIO");
    expect(perms).not.toContain("android.permission.SYSTEM_ALERT_WINDOW");
  });

  it("does NOT declare manual intentFilters for the Health Connect rationale", () => {
    // Expo's intent-filter normalizer prepends `android.intent.action.`
    // and `android.intent.category.` to the action / category names,
    // which silently mangles `androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE`
    // into a broken action name. The `react-native-health-connect`
    // plugin adds the same intent-filter via withAndroidManifest where
    // the values land verbatim — so this list MUST stay empty for the
    // Health Connect consent flow to work.
    const config = loadConfig();
    const filters = config.android?.intentFilters ?? [];
    const mangleable = filters.filter((f) =>
      String(f.action ?? "").includes("ACTION_SHOW_PERMISSIONS_RATIONALE")
    );
    expect(mangleable).toEqual([]);
  });

  it("loads the react-native-health-connect plugin (adds the rationale intent-filter correctly)", () => {
    const config = loadConfig();
    const plugins = (config.plugins ?? []).map((p) =>
      Array.isArray(p) ? p[0] : p
    );
    expect(plugins).toContain("react-native-health-connect");
  });

  it("loads the local Android-hardening plugin (queries + uses-feature + allowBackup)", () => {
    const config = loadConfig();
    const plugins = (config.plugins ?? []).map((p) =>
      Array.isArray(p) ? p[0] : p
    );
    expect(plugins).toContain("./plugins/withAndroidHardening.js");
  });

  it("disables recordAudioAndroid + microphonePermission on the image-capture plugins", () => {
    const config = loadConfig();
    const plugins = config.plugins ?? [];
    function findEntry(name: string): Record<string, unknown> | undefined {
      const entry = plugins.find(
        (p): p is [string, Record<string, unknown>] =>
          Array.isArray(p) && p[0] === name
      );
      return entry?.[1];
    }

    const camera = findEntry("expo-camera");
    expect(camera?.recordAudioAndroid).toBe(false);
    expect(camera?.microphonePermission).toBe(false);

    const picker = findEntry("expo-image-picker");
    expect(picker?.microphonePermission).toBe(false);
  });

  it("derives versionCode from ANDROID_VERSION_CODE then EAS_BUILD_NUMBER", () => {
    process.env.ANDROID_VERSION_CODE = "42";
    expect(loadConfig().android?.versionCode).toBe(42);

    delete process.env.ANDROID_VERSION_CODE;
    process.env.EAS_BUILD_NUMBER = "17";
    expect(loadConfig().android?.versionCode).toBe(17);

    delete process.env.EAS_BUILD_NUMBER;
    expect(loadConfig().android?.versionCode).toBe(1);
  });

  it("ignores garbage values in the version-code env vars", () => {
    process.env.ANDROID_VERSION_CODE = "1.0.0";
    expect(loadConfig().android?.versionCode).toBe(1);

    process.env.ANDROID_VERSION_CODE = "abc";
    expect(loadConfig().android?.versionCode).toBe(1);
  });

  it("uses the dev bundle id by default (channel-prefixed bundle map)", () => {
    // We can only test one channel per jest run because
    // `babel-preset-expo`'s inline-env-vars plugin bakes
    // `process.env.EXPO_PUBLIC_BUILD_CHANNEL` into the transformed
    // module at transform time. The other channels are exercised by
    // EAS build, which sets EXPO_PUBLIC_BUILD_CHANNEL=staging|prod
    // through `eas.json` BEFORE the babel transform runs.
    expect(loadConfig().android?.package).toMatch(
      /^com\.healthos\.app(\.dev|\.staging)?$/
    );
  });

  it("uses adjustResize keyboard mode (chat composer + form fields lift correctly)", () => {
    const config = loadConfig();
    expect(config.android?.softwareKeyboardLayoutMode).toBe("resize");
  });
});

describe("withAndroidHardening helpers", () => {
  // Drive the helpers directly. The full plugin chain runs at
  // `expo prebuild` time and depends on a complete ExpoConfig graph;
  // these unit tests pin the actual manifest mutations.
  const {
    ensureQueriesPackage,
    ensureUsesFeatureOptional,
    HEALTH_CONNECT_PACKAGE,
    CAMERA_FEATURES,
    BLOCKED_PERMISSIONS,
  } = require("../../plugins/withAndroidHardening.js").__test__ as {
    ensureQueriesPackage: (
      m: Record<string, unknown>,
      p: string
    ) => void;
    ensureUsesFeatureOptional: (
      m: Record<string, unknown>,
      f: string
    ) => void;
    HEALTH_CONNECT_PACKAGE: string;
    CAMERA_FEATURES: string[];
    BLOCKED_PERMISSIONS: string[];
  };

  it("knows the Health Connect package name verbatim", () => {
    expect(HEALTH_CONNECT_PACKAGE).toBe("com.google.android.apps.healthdata");
  });

  it("ensureQueriesPackage adds <queries><package> on a fresh manifest", () => {
    const manifest: Record<string, unknown> = {};
    ensureQueriesPackage(manifest, HEALTH_CONNECT_PACKAGE);
    const queries = manifest.queries as { package: { $: Record<string, string> }[] }[];
    expect(queries[0]?.package?.[0]?.$["android:name"]).toBe(
      HEALTH_CONNECT_PACKAGE
    );
  });

  it("ensureQueriesPackage is idempotent (no duplicate on second run)", () => {
    const manifest: Record<string, unknown> = {};
    ensureQueriesPackage(manifest, HEALTH_CONNECT_PACKAGE);
    ensureQueriesPackage(manifest, HEALTH_CONNECT_PACKAGE);
    ensureQueriesPackage(manifest, HEALTH_CONNECT_PACKAGE);
    const queries = manifest.queries as { package: { $: Record<string, string> }[] }[];
    expect(queries[0]?.package).toHaveLength(1);
  });

  it("ensureQueriesPackage merges into a manifest that already has an <intent>", () => {
    const manifest: Record<string, unknown> = {
      queries: [
        {
          intent: [{ action: [{ $: { "android:name": "android.intent.action.VIEW" } }] }],
        },
      ],
    };
    ensureQueriesPackage(manifest, HEALTH_CONNECT_PACKAGE);
    const queries = manifest.queries as {
      intent?: unknown[];
      package?: { $: Record<string, string> }[];
    }[];
    // The original <intent> element survives.
    expect(queries[0]?.intent).toHaveLength(1);
    // And we appended the <package>.
    expect(queries[0]?.package?.[0]?.$["android:name"]).toBe(
      HEALTH_CONNECT_PACKAGE
    );
  });

  it("ensureUsesFeatureOptional adds the feature with required=false", () => {
    const manifest: Record<string, unknown> = {};
    for (const f of CAMERA_FEATURES) {
      ensureUsesFeatureOptional(manifest, f);
    }
    const features = manifest["uses-feature"] as { $: Record<string, string> }[];
    for (const name of CAMERA_FEATURES) {
      const found = features.find((f) => f.$["android:name"] === name);
      expect(found).toBeDefined();
      expect(found!.$["android:required"]).toBe("false");
    }
  });

  it("ensureUsesFeatureOptional flips an existing required=true entry to false", () => {
    const manifest: Record<string, unknown> = {
      "uses-feature": [
        {
          $: {
            "android:name": "android.hardware.camera",
            "android:required": "true",
          },
        },
      ],
    };
    ensureUsesFeatureOptional(manifest, "android.hardware.camera");
    const features = manifest["uses-feature"] as { $: Record<string, string> }[];
    expect(features).toHaveLength(1);
    expect(features[0]!.$["android:required"]).toBe("false");
  });

  it("blocks the privacy-sensitive permissions that upstream plugins add by accident", () => {
    expect(BLOCKED_PERMISSIONS).toContain("android.permission.SYSTEM_ALERT_WINDOW");
  });
});
