export const queryKeys = {
  session: 'session',
  dashboard: 'dashboard.summary',
  vitals: (days: number) => `vitals.timeseries.${days}`,
  reminders: 'reminders.upcoming',
  appointments: 'appointments.list',
  appointment: (id: string) => `appointments.detail.${id}`,
  appointmentPrep: (id: string) => `appointments.prep.${id}`,
  prescriptionAssets: (appointmentId: string) => `appointments.prescription-assets.${appointmentId}`,
  conversations: 'chat.conversations',
  messages: (conversationId: string) => `chat.messages.${conversationId}`,
  medications: 'medications.list',
  medication: (id: string) => `medications.detail.${id}`,
  medicationAdherence: (id: string, period: string) => `medications.adherence.${id}.${period}`,
  medicationDosesToday: 'medications.today',
  profile: 'profile.me',
  preferences: 'preferences.me',
  notifications: 'notifications.list',
  notificationPreferences: 'notifications.preferences',
  unreadNotifications: 'notifications.unread',
  remindersAll: 'reminders.list',
  reminderOccurrences: (rangeKey: string) => `reminders.occurrences.${rangeKey}`,
  meals: (rangeKey: string) => `meals.list.${rangeKey}`,
  meal: (id: string) => `meals.detail.${id}`,
  mealIngredients: (id: string) => `meals.ingredients.${id}`,
  mealCaloriesSummary: (rangeKey: string) => `meals.calories.${rangeKey}`,
  nutritionSuggestions: 'nutrition.suggestions',
  reports: (period: string) => `reports.${period}`,
  reportTrend: (metric: string, period: string) => `reports.trend.${metric}.${period}`,
  reportTrendBatch: (metrics: string, period: string) => `reports.trend-batch.${metrics}.${period}`,
  riskSummary: 'risk.summary',
  healthGoal: 'health-goals.current',
  healthGoalProgress: (metric: string, period: string) => `goals.progress.${metric}.${period}`,
  devices: 'devices.list',
  device: (id: string) => `devices.detail.${id}`,
  deviceSyncState: (id: string) => `devices.sync-state.${id}`,
  emergencyProfile: 'emergency.profile',
  emergencyTokens: 'emergency.tokens',
  emergencyAccessLogs: 'emergency.access-logs',
  mfaStatus: 'security.mfa-status',
  securityLogs: 'security.logs',
};
