"""STRETCH P5 — Synchronous PDF rendering for a Visit Brief.

The MVP path uses browser print (`/print` page + `@media print` CSS) — that
ships zero infra dependency and works today. This module is the stretch
extension: a real PDF download generated server-side via WeasyPrint, mirroring
the scaffolding from `app.tasks.report_pdf` but skipping Celery because a
visit brief is small (single page) and rendering takes <500ms.

Falls back gracefully to a `PdfRenderUnavailable` error if WeasyPrint or its
system dependencies (Cairo / Pango) are missing — the FE displays the
"Print" link instead so the feature degrades cleanly.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from app.models.visit_briefs import ConcernCategoryEnum, VisitBrief

logger = logging.getLogger(__name__)


TEMPLATE_DIR = (
    Path(__file__).resolve().parent.parent / "templates" / "visit_briefs"
)
TEMPLATE_NAME = "visit-brief.html.j2"


# Locale-specific copy. Kept tiny and frozen — the FE has the rich i18n bank;
# this is the printable surface only.
_LABELS = {
    "en": {
        "title": "Pre-Visit Brief",
        "disclaimer": (
            "This brief was prepared by a patient using a self-help tool. "
            "It does not diagnose. It is meant to help focus the conversation."
        ),
        "concerns_header": "Concerns",
        "questions_header": "Questions to ask",
        "routing_header": "Suggested next step",
        "ruleset_version": "Ruleset",
        "finalized_at": "Finalized",
        "footer_note": (
            "Generated by HealthOS Pre-Visit Brief. Not a medical record."
        ),
        "triggers": "Triggers",
        "better_with": "Better with",
        "worse_with": "Worse with",
        "meds_taken": "Meds taken",
        "prior_care": "Prior care",
    },
    "vi": {
        "title": "Bản chuẩn bị khám",
        "disclaimer": (
            "Bản này do bệnh nhân tự chuẩn bị bằng công cụ hỗ trợ. "
            "Không phải chẩn đoán. Dùng để hỗ trợ trao đổi với bác sĩ."
        ),
        "concerns_header": "Vấn đề",
        "questions_header": "Câu hỏi muốn hỏi",
        "routing_header": "Gợi ý bước tiếp theo",
        "ruleset_version": "Bộ quy tắc",
        "finalized_at": "Hoàn tất",
        "footer_note": (
            "Tạo bởi HealthOS Pre-Visit Brief. Không phải bệnh án."
        ),
        "triggers": "Yếu tố",
        "better_with": "Đỡ hơn khi",
        "worse_with": "Tệ hơn khi",
        "meds_taken": "Thuốc đã dùng",
        "prior_care": "Đã được chăm sóc",
    },
}

_VISIT_TYPE_LABELS = {
    "en": {
        "gp_routine": "Routine GP visit",
        "specialist": "Specialist visit",
        "follow_up": "Follow-up visit",
        "mental_health": "Mental health visit",
        "urgent_walkin": "Urgent / walk-in",
        "pediatric_caregiver": "Caregiver brief (child)",
    },
    "vi": {
        "gp_routine": "Khám tổng quát định kỳ",
        "specialist": "Khám chuyên khoa",
        "follow_up": "Tái khám",
        "mental_health": "Khám sức khỏe tâm thần",
        "urgent_walkin": "Khám gấp / không hẹn",
        "pediatric_caregiver": "Bản chuẩn bị cho trẻ em",
    },
}

_CATEGORY_LABELS = {
    "en": {
        ConcernCategoryEnum.PAIN.value: "Pain",
        ConcernCategoryEnum.FEVER.value: "Fever",
        ConcernCategoryEnum.GI.value: "Stomach / digestion",
        ConcernCategoryEnum.RESP.value: "Breathing",
        ConcernCategoryEnum.MENTAL.value: "Mental health",
        ConcernCategoryEnum.SKIN.value: "Skin",
        ConcernCategoryEnum.NEURO.value: "Brain / nerves",
        ConcernCategoryEnum.CARDIO.value: "Heart / chest",
        ConcernCategoryEnum.OTHER.value: "Other",
    },
    "vi": {
        ConcernCategoryEnum.PAIN.value: "Đau",
        ConcernCategoryEnum.FEVER.value: "Sốt",
        ConcernCategoryEnum.GI.value: "Tiêu hóa",
        ConcernCategoryEnum.RESP.value: "Hô hấp",
        ConcernCategoryEnum.MENTAL.value: "Tâm lý",
        ConcernCategoryEnum.SKIN.value: "Da liễu",
        ConcernCategoryEnum.NEURO.value: "Thần kinh",
        ConcernCategoryEnum.CARDIO.value: "Tim mạch",
        ConcernCategoryEnum.OTHER.value: "Khác",
    },
}


class PdfRenderUnavailable(RuntimeError):
    """Raised when WeasyPrint or its system deps aren't installed.

    The endpoint catches this and surfaces a 503 so the FE can fall back to
    the existing browser-print path. Never retried — this is a deployment
    issue, not a transient one.
    """


def _serialize_brief(brief: VisitBrief) -> dict[str, Any]:
    """Project the ORM brief into a plain dict for the Jinja template.

    Done inline so the template never imports ORM models. Fields the template
    accesses must be present here.
    """
    return {
        "id": str(brief.id),
        "visit_type": brief.visit_type,
        "status": brief.status,
        "revision": brief.revision,
        "title": brief.title,
        "finalized_at": brief.finalized_at.isoformat() if brief.finalized_at else None,
        "created_at": brief.created_at.isoformat() if brief.created_at else None,
        "symptoms": [
            {
                "id": str(s.id),
                "concern_text": s.concern_text,
                "concern_category": s.concern_category,
                "severity_0_10": s.severity_0_10,
                "duration_value": s.duration_value,
                "duration_unit": s.duration_unit,
                "triggers": s.triggers,
                "better_with": s.better_with,
                "worse_with": s.worse_with,
                "meds_taken": s.meds_taken,
                "prior_care": s.prior_care,
            }
            for s in (brief.symptoms or [])
        ],
    }


def render_html(brief: VisitBrief, *, locale: str) -> str:
    """Render the brief HTML deterministically. Cheap; no I/O."""
    from jinja2 import Environment, FileSystemLoader, select_autoescape

    loc = locale if locale in _LABELS else "en"
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        autoescape=select_autoescape(["html", "j2"]),
    )
    template = env.get_template(TEMPLATE_NAME)

    questions = []
    if brief.question_set and brief.question_set.questions:
        questions = sorted(brief.question_set.questions, key=lambda q: q.get("order", 0))

    triage = None
    if brief.triage_outcomes:
        latest = max(brief.triage_outcomes, key=lambda t: t.computed_at)
        triage = {
            "bucket": latest.bucket,
            "ruleset_version": latest.ruleset_version,
            "matched_signals": latest.matched_signals,
            "computed_at": latest.computed_at.isoformat(),
        }

    return template.render(
        brief=_serialize_brief(brief),
        locale=loc,
        labels=_LABELS[loc],
        category_labels=_CATEGORY_LABELS[loc],
        visit_type_label=_VISIT_TYPE_LABELS[loc].get(brief.visit_type, brief.visit_type),
        questions=questions,
        triage=triage,
    )


def render_pdf(brief: VisitBrief, *, locale: str) -> bytes:
    """Render the brief as a PDF. Raises PdfRenderUnavailable if WeasyPrint
    (or its Cairo/Pango system deps) is missing on this host.
    """
    html = render_html(brief, locale=locale)
    try:
        from weasyprint import HTML  # noqa: WPS433 — defer heavy import
    except ImportError as exc:
        logger.info("WeasyPrint unavailable: %s", exc)
        raise PdfRenderUnavailable(
            "WeasyPrint is not installed on this host. Install WeasyPrint and "
            "its system dependencies (Cairo, Pango) to enable server-side PDF "
            "rendering. The browser print page remains available as a fallback."
        ) from exc
    return HTML(string=html).write_pdf()
