#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = path.resolve(SCRIPT_DIR, "../..");
const DEFAULT_MASTER = path.join(DEFAULT_ROOT, "infra/env/.env.master");
const GENERATED_HEADER = [
  "# Generated by infra/scripts/render-env.mjs from infra/env/.env.master.",
  "# Do not edit this file directly; update the master env and rerun sync-env.",
  "",
];

const TARGETS = {
  backend: {
    path: "backend/.env",
    sections: [
      ["App", ["APP_ENV", "NODE_ENV", "DEBUG", "LOG_LEVEL", "LOG_FORMAT", "APP_URL"]],
      ["Database and Redis", ["DATABASE_URL", "DB_DISABLE_POOL", "REDIS_URL", "CELERY_BROKER_URL"]],
      [
        "Storage",
        [
          "STORAGE_ENDPOINT",
          "STORAGE_ACCESS_KEY",
          "STORAGE_SECRET_KEY",
          "STORAGE_BUCKET_MEALS",
          "STORAGE_BUCKET_DOCS",
          "STORAGE_USE_SSL",
        ],
      ],
      [
        "Security",
        [
          "SECRET_KEY",
          "ALGORITHM",
          "ACCESS_TOKEN_EXPIRE_MINUTES",
          "REFRESH_TOKEN_EXPIRE_DAYS",
          "AUTH_ISSUER",
          "AUTH_AUDIENCE",
          "FERNET_KEY",
          "ALLOWED_ORIGINS",
          "BFF_SHARED_SECRET",
          "BFF_EXCHANGE_ISSUER",
          "BFF_EXCHANGE_AUDIENCE",
          "BFF_EXCHANGE_MAX_AGE_SECONDS",
          "METRICS_TOKEN",
          "METRICS_ALLOW_LOCAL",
        ],
      ],
      ["Service URLs", ["AI_WORKER_URL"]],
      ["Email", ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "SMTP_FROM", "SMTP_USE_TLS"]],
    ],
  },
  frontend: {
    path: "frontend/.env.local",
    sections: [
      ["BFF server runtime", ["CORE_API_URL", "REDIS_URL", "TRUST_PROXY"]],
      [
        "Auth cookies and CSRF",
        [
          "COOKIE_NAME",
          "COOKIE_MAX_AGE",
          "COOKIE_SECURE",
          "REFRESH_COOKIE_NAME",
          "REFRESH_COOKIE_MAX_AGE",
          "BFF_TRUSTED_ORIGINS",
          "BFF_CSRF_GUARD_MODE",
        ],
      ],
      ["NextAuth", ["NEXTAUTH_URL", "NEXTAUTH_SECRET"]],
      [
        "OAuth",
        [
          "ALLOWED_DEV_ORIGINS",
          "GOOGLE_CLIENT_ID",
          "GOOGLE_CLIENT_SECRET",
          "OAUTH_GOOGLE_CALLBACK_URL",
          "OAUTH_GOOGLE_LINK_CALLBACK_URL",
          "GITHUB_CLIENT_ID",
          "GITHUB_CLIENT_SECRET",
          "OAUTH_GITHUB_CALLBACK_URL",
          "OAUTH_GITHUB_LINK_CALLBACK_URL",
          "MOBILE_OAUTH_REDIRECT_URIS",
          "ANDROID_APP_LINK_PACKAGE_NAME",
          "ANDROID_APP_LINK_SHA256_CERT_FINGERPRINTS",
          "BFF_SHARED_SECRET",
        ],
      ],
      [
        "Public browser env",
        [
          "NEXT_PUBLIC_APP_URL",
          "NEXT_PUBLIC_WS_URL",
          "NEXT_PUBLIC_CORE_WS_URL",
          "NEXT_PUBLIC_APP_ENV",
          "NEXT_PUBLIC_ONBOARDING_DRAFT_SERVER",
        ],
      ],
      ["Feature flags", ["ADMIN_SECURITY_FEED_ENABLED", "ADMIN_AUDIT_FEED_ENABLED", "DEV_BYPASS_ENABLED", "DEV_BYPASS_CREDENTIALS"]],
    ],
  },
  "ai-worker": {
    path: "services/ai-worker/.env",
    sections: [
      ["App", ["DEBUG", "LOG_LEVEL"]],
      ["Service URLs", ["REDIS_URL", "CORE_API_URL"]],
      [
        "Storage",
        [
          "STORAGE_ENDPOINT",
          "STORAGE_ACCESS_KEY",
          "STORAGE_SECRET_KEY",
          "STORAGE_BUCKET_MEALS",
          "STORAGE_USE_SSL",
        ],
      ],
      [
        "AI",
        [
          "AI_MODEL_PATH",
          "AI_CONFIDENCE_THRESHOLD",
          "AI_YOLO_TIMEOUT_SECONDS",
          "AI_FOOD_ANALYSIS_ENABLED",
          "AI_FOOD_ANALYSIS_TIMEOUT_SECONDS",
          "AI_CALORIECLIP_ENABLED",
          "AI_CALORIECLIP_TIMEOUT_SECONDS",
          "AI_CALORIE_RANGE_RATIO",
          "AI_MAX_IMAGE_SIZE_PX",
          "AI_FOOD_ANALYSIS_REPO_ID",
          "AI_CALORIECLIP_REPO_ID",
          "AI_FOOD_ANALYSIS_MODEL_PATH",
          "AI_CALORIECLIP_MODEL_PATH",
          "AI_YOLO_MODEL_PATH",
          "AI_YOLO_GDRIVE_FILE_ID",
          "AI_YOLO_MODEL_SHA256",
          "AI_CLASS_NAMES_PATH",
          "AI_REQUEST_TIMEOUT_SECONDS",
          "AI_ALLOWED_IMAGE_HOSTS",
          "AI_IMAGE_DOWNLOAD_TIMEOUT_SECONDS",
          "AI_BLOCK_PRIVATE_NETWORKS",
          "AI_PROXY_BASE_URL",
          "AI_PROXY_MODEL",
          "AI_PROXY_API_KEY",
          "AI_PROXY_THINKING_MODE",
          "AI_PROXY_REASONING_EFFORT",
          "AI_EMBEDDING_MODEL",
          "AI_EMBEDDING_DIMENSION",
          "AI_EMBEDDING_TIMEOUT_SECONDS",
          "AI_CHAT_MAX_TOKENS",
          "AI_CHAT_TEMPERATURE",
          "AI_CHAT_TIMEOUT_SECONDS",
          "AI_CHAT_STREAM_CHUNK_MIN_CHARS",
        ],
      ],
    ],
  },
  "queue-worker": {
    path: "services/queue-worker/.env",
    sections: [
      ["App", ["DEBUG", "LOG_LEVEL"]],
      ["Queues", ["REDIS_URL", "CELERY_BROKER_URL", "CELERY_RESULT_BACKEND"]],
      ["Service URLs", ["CORE_API_URL", "AI_WORKER_URL"]],
      [
        "Storage",
        [
          "STORAGE_ENDPOINT",
          "STORAGE_ACCESS_KEY",
          "STORAGE_SECRET_KEY",
          "STORAGE_BUCKET_MEALS",
          "STORAGE_USE_SSL",
        ],
      ],
    ],
  },
  notification: {
    path: "services/notification/.env",
    sections: [
      ["App", ["DEBUG", "LOG_LEVEL"]],
      ["Service URLs", ["CORE_API_URL"]],
      ["Email", ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "SMTP_FROM", "SMTP_USE_TLS"]],
      ["Firebase", ["FIREBASE_PROJECT_ID", "FIREBASE_PRIVATE_KEY", "FIREBASE_CLIENT_EMAIL"]],
    ],
  },
  "compose-dev": {
    path: "infra/docker/.env.dev",
    sections: [
      [
        "Docker Compose dev substitution values",
        [
          "POSTGRES_DB",
          "POSTGRES_USER",
          "POSTGRES_PASSWORD",
          "REDIS_PASSWORD",
          "MINIO_ROOT_USER",
          "MINIO_ROOT_PASSWORD",
          "NEXTAUTH_SECRET",
          "BFF_SHARED_SECRET",
          "AI_WORKER_URL",
        ],
      ],
    ],
  },
  "compose-prod": {
    path: "infra/docker/.env.prod",
    sections: [
      [
        "Docker Compose production substitution values",
        [
          "POSTGRES_DB",
          "POSTGRES_USER",
          "POSTGRES_PASSWORD",
          "REDIS_PASSWORD",
          "MINIO_ROOT_USER",
          "MINIO_ROOT_PASSWORD",
          "STORAGE_ENDPOINT",
          "NEXTAUTH_URL",
          "NEXTAUTH_SECRET",
          "NEXT_PUBLIC_APP_URL",
          "NEXT_PUBLIC_WS_URL",
          "NEXT_PUBLIC_CORE_WS_URL",
          "BFF_TRUSTED_ORIGINS",
          "BFF_CSRF_GUARD_MODE",
          "DEV_BYPASS_ENABLED",
          "DEV_BYPASS_CREDENTIALS",
          "BFF_SHARED_SECRET",
          "METRICS_TOKEN",
        ],
      ],
    ],
  },
  mobile: {
    path: "mobile/.env",
    sections: [["Expo public build-time env", [
      "EXPO_PUBLIC_API_URL",
      "EXPO_PUBLIC_CORE_API_URL",
      "EXPO_PUBLIC_WS_URL",
      "EXPO_PUBLIC_CORE_WS_URL",
      "EXPO_PUBLIC_WEB_APP_URL",
      "EXPO_PUBLIC_MOBILE_OAUTH_REDIRECT_URI",
    ]]],
  },
};

const TARGET_ALIASES = {
  all: Object.keys(TARGETS),
  dev: ["backend", "frontend", "ai-worker", "queue-worker", "notification", "compose-dev", "mobile"],
  prod: ["backend", "frontend", "ai-worker", "queue-worker", "notification", "compose-prod", "mobile"],
  workers: ["ai-worker", "queue-worker", "notification"],
};

const SECRET_KEY_PATTERN = /(SECRET|PASSWORD|TOKEN|PRIVATE|FERNET|API_KEY|CLIENT_SECRET|ACCESS_KEY)/i;
const PLACEHOLDER_PATTERN = /(change-me|replace-with|your-domain|example\.com|dev-secret|dev-bff-secret|dev-nextauth|healthos_dev_pass|minioadmin)/i;
const PROTECTED_ENV_VALUES = new Set(["production", "prod", "staging"]);
const ANDROID_PACKAGE_RE = /^([A-Za-z][A-Za-z0-9_]*\.)+[A-Za-z][A-Za-z0-9_]*$/;
const ANDROID_SHA256_FINGERPRINT_RE = /^([0-9A-F]{2}:){31}[0-9A-F]{2}$/;
// Maps legacy key names to their canonical replacements.
// When the legacy key is present and the new key is absent/empty, the value is
// forwarded automatically and a deprecation warning is emitted to stderr.
const LEGACY_KEY_MAP = {
  NEXT_PUBLIC_CORE_WS_URL: "NEXT_PUBLIC_WS_URL",
  EXPO_PUBLIC_CORE_WS_URL: "EXPO_PUBLIC_WS_URL",
};

const LOCAL_MOBILE_EMULATOR_DEFAULTS = new Map([
  ["EXPO_PUBLIC_API_URL", "http://10.0.2.2:3000"],
  ["EXPO_PUBLIC_CORE_API_URL", "http://10.0.2.2:8000"],
  ["EXPO_PUBLIC_WS_URL", "ws://10.0.2.2:8000"],
  ["EXPO_PUBLIC_CORE_WS_URL", "ws://10.0.2.2:8000"],
  ["EXPO_PUBLIC_WEB_APP_URL", "http://10.0.2.2:3000"],
]);
const BACKWARD_COMPATIBLE_DEFAULTS = {
  DB_DISABLE_POOL: "false",
  DEV_BYPASS_ENABLED: "false",
  EXPO_PUBLIC_API_URL: "",
  EXPO_PUBLIC_CORE_API_URL: "",
  EXPO_PUBLIC_WS_URL: "",
  EXPO_PUBLIC_CORE_WS_URL: "",
  EXPO_PUBLIC_WEB_APP_URL: "",
  EXPO_PUBLIC_MOBILE_OAUTH_REDIRECT_URI: "",
  ANDROID_APP_LINK_PACKAGE_NAME: "com.nt208.healthos",
  ANDROID_APP_LINK_SHA256_CERT_FINGERPRINTS: "",
};

export function applyEnvDefaults(env) {
  const base = { ...BACKWARD_COMPATIBLE_DEFAULTS, ...env };
  // Forward legacy keys to canonical names when new key is absent or empty.
  // Uses || (not ??) so that empty-string injections are treated as "not set".
  for (const [legacyKey, newKey] of Object.entries(LEGACY_KEY_MAP)) {
    const resolved = (base[newKey] || "").trim() || (base[legacyKey] || "").trim();
    if (resolved) {
      if (!(base[newKey] || "").trim() && (base[legacyKey] || "").trim()) {
        process.stderr.write(
          `[render-env] DEPRECATED: ${legacyKey} → rename to ${newKey} (will be removed next release)\n`,
        );
      }
      base[newKey] = resolved;
    }
  }
  return base;
}

export function parseDotenv(text) {
  const env = {};
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/);
  for (const [index, originalLine] of lines.entries()) {
    const line = originalLine.trim();
    if (!line || line.startsWith("#")) continue;
    const match = line.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match) {
      throw new Error(`Invalid env line ${index + 1}: ${originalLine}`);
    }
    env[match[1]] = parseValue(match[2]);
  }
  return env;
}

function parseValue(rawValue) {
  let value = rawValue.trim();
  if (!value) return "";
  const quote = value[0];
  if ((quote === '"' || quote === "'") && value.endsWith(quote)) {
    value = value.slice(1, -1);
    if (quote === '"') {
      value = value.replace(/\\n/g, "\n").replace(/\\r/g, "\r").replace(/\\t/g, "\t").replace(/\\"/g, '"').replace(/\\\\/g, "\\");
    }
    return value;
  }
  const commentIndex = findInlineComment(value);
  if (commentIndex !== -1) value = value.slice(0, commentIndex).trimEnd();
  return value;
}

function findInlineComment(value) {
  for (let index = 0; index < value.length; index += 1) {
    if (value[index] === "#" && (index === 0 || /\s/.test(value[index - 1]))) {
      return index;
    }
  }
  return -1;
}

export function stringifyEnvValue(value) {
  const text = String(value ?? "");
  if (text === "") return "";
  if ((text.startsWith("[") && text.endsWith("]")) || (text.startsWith("{") && text.endsWith("}"))) return text;
  if (/[\r\n]/.test(text)) return JSON.stringify(text);
  if (/^\s|\s$|[\s#"'`$\\]/.test(text)) return JSON.stringify(text);
  return text;
}

export function resolveTargetNames(target) {
  const requested = target || "all";
  const names = TARGET_ALIASES[requested] ?? [requested];
  for (const name of names) {
    if (!TARGETS[name]) {
      throw new Error(`Unknown target "${name}". Valid targets: ${Object.keys(TARGETS).join(", ")}, all, dev, prod, workers`);
    }
  }
  return names;
}

export function collectTargetKeys(targetNames) {
  const keys = new Set();
  for (const name of targetNames) {
    for (const [, sectionKeys] of TARGETS[name].sections) {
      for (const key of sectionKeys) keys.add(key);
    }
  }
  return [...keys].sort();
}

export function validateEnv(env, targetNames, options = {}) {
  const effectiveEnv = applyEnvDefaults(env);
  const requiredKeys = collectTargetKeys(targetNames);
  const missing = requiredKeys.filter((key) => !(key in effectiveEnv));
  if (missing.length > 0) {
    throw new Error(`Master env is missing required key(s): ${missing.join(", ")}`);
  }

  for (const key of requiredKeys) assertPublicKeyIsSafe(key);

  const requireProd = options.requireProdValidation || isProtectedEnv(effectiveEnv);
  if (!requireProd) return;

  const prodRequired = [
    "SECRET_KEY",
    "BFF_SHARED_SECRET",
    "DATABASE_URL",
    "REDIS_URL",
    "ALLOWED_ORIGINS",
    "STORAGE_ACCESS_KEY",
    "STORAGE_SECRET_KEY",
    "GOOGLE_CLIENT_SECRET",
    "GITHUB_CLIENT_SECRET",
    "FERNET_KEY",
    "METRICS_TOKEN",
    "NEXTAUTH_URL",
    "NEXTAUTH_SECRET",
    "BFF_TRUSTED_ORIGINS",
    "POSTGRES_PASSWORD",
    "REDIS_PASSWORD",
    "MINIO_ROOT_USER",
    "MINIO_ROOT_PASSWORD",
    "NEXT_PUBLIC_APP_URL",
    "EXPO_PUBLIC_WEB_APP_URL",
    "EXPO_PUBLIC_MOBILE_OAUTH_REDIRECT_URI",
    "ANDROID_APP_LINK_PACKAGE_NAME",
    "ANDROID_APP_LINK_SHA256_CERT_FINGERPRINTS",
  ];
  const mobileApiKey = assertAtLeastOne(
    effectiveEnv,
    ["EXPO_PUBLIC_API_URL", "EXPO_PUBLIC_CORE_API_URL"],
    "Production requires EXPO_PUBLIC_API_URL (preferred) or EXPO_PUBLIC_CORE_API_URL.",
  );
  // Resolve canonical WS keys (applyEnvDefaults already forwarded legacy → new).
  const webWsKey = assertAtLeastOne(
    effectiveEnv,
    ["NEXT_PUBLIC_WS_URL", "NEXT_PUBLIC_CORE_WS_URL"],
    "Production requires NEXT_PUBLIC_WS_URL (preferred) or NEXT_PUBLIC_CORE_WS_URL.",
  );
  const mobileWsKey = assertAtLeastOne(
    effectiveEnv,
    ["EXPO_PUBLIC_WS_URL", "EXPO_PUBLIC_CORE_WS_URL"],
    "Production requires EXPO_PUBLIC_WS_URL (preferred) or EXPO_PUBLIC_CORE_WS_URL.",
  );
  for (const key of prodRequired) {
    assertPresent(effectiveEnv, key);
    assertNotPlaceholder(effectiveEnv, key);
  }
  assertPresent(effectiveEnv, webWsKey);
  assertNotPlaceholder(effectiveEnv, webWsKey);
  assertPresent(effectiveEnv, mobileWsKey);
  assertNotPlaceholder(effectiveEnv, mobileWsKey);

  assertMinLength(effectiveEnv, "SECRET_KEY", 32);
  assertMinLength(effectiveEnv, "BFF_SHARED_SECRET", 32);
  assertMinLength(effectiveEnv, "METRICS_TOKEN", 16);
  assertMinLength(effectiveEnv, "NEXTAUTH_SECRET", 32);
  assertNoLocalhost(effectiveEnv, "DATABASE_URL");
  assertNoLocalhost(effectiveEnv, "REDIS_URL");
  assertNoLocalhost(effectiveEnv, "ALLOWED_ORIGINS");
  assertNoLocalhost(effectiveEnv, "EXPO_PUBLIC_MOBILE_OAUTH_REDIRECT_URI");
  assertNoLocalhost(effectiveEnv, mobileApiKey);
  assertNoLocalhost(effectiveEnv, webWsKey);
  assertNoWildcardOrigins(effectiveEnv.ALLOWED_ORIGINS);
  assertHttps(effectiveEnv, "NEXTAUTH_URL");
  assertHttps(effectiveEnv, "NEXT_PUBLIC_APP_URL");
  assertHttps(effectiveEnv, mobileApiKey);
  assertHttps(effectiveEnv, "EXPO_PUBLIC_WEB_APP_URL");
  assertHttps(effectiveEnv, "EXPO_PUBLIC_MOBILE_OAUTH_REDIRECT_URI");
  assertWss(effectiveEnv, webWsKey);
  assertWss(effectiveEnv, mobileWsKey);
  assertAndroidPackageName(effectiveEnv.ANDROID_APP_LINK_PACKAGE_NAME);
  assertAndroidSha256Fingerprints(effectiveEnv.ANDROID_APP_LINK_SHA256_CERT_FINGERPRINTS);
  assertMobileOAuthRedirectAllowlist(effectiveEnv);
  assertTrustedOrigins(effectiveEnv.BFF_TRUSTED_ORIGINS);
  assertCsrfGuardEnforcedInProtectedEnv(effectiveEnv);
  assertNoDevBypassInProtectedEnv(effectiveEnv);
  assertCookieTtlMatchesAccessToken(effectiveEnv);
}

function isProtectedEnv(env) {
  return [env.APP_ENV, env.NEXT_PUBLIC_APP_ENV, env.NODE_ENV].some((value) =>
    PROTECTED_ENV_VALUES.has(String(value ?? "").trim().toLowerCase()),
  );
}

export function assertPublicKeyIsSafe(key) {
  if ((key.startsWith("NEXT_PUBLIC_") || key.startsWith("EXPO_PUBLIC_")) && SECRET_KEY_PATTERN.test(key)) {
    throw new Error(`Public env key "${key}" looks secret-like. Server-only secrets must not use public prefixes.`);
  }
}

function assertPresent(env, key) {
  if (!String(env[key] ?? "").trim()) {
    throw new Error(`Production env requires non-empty ${key}`);
  }
}

function assertAtLeastOne(env, keys, message) {
  const present = keys.find((key) => String(env[key] ?? "").trim());
  if (!present) {
    throw new Error(message);
  }
  return present;
}

function assertNotPlaceholder(env, key) {
  const value = String(env[key] ?? "");
  if (PLACEHOLDER_PATTERN.test(value)) {
    throw new Error(`Production env key ${key} still contains a placeholder/development value`);
  }
}

function assertMinLength(env, key, min) {
  if (String(env[key] ?? "").trim().length < min) {
    throw new Error(`Production env key ${key} must be at least ${min} characters`);
  }
}

function assertNoLocalhost(env, key) {
  const value = String(env[key] ?? "").toLowerCase();
  if (/(localhost|127\.0\.0\.1|10\.0\.2\.2)/.test(value)) {
    throw new Error(`Production env key ${key} must not point at localhost/emulator addresses`);
  }
}

function assertNoWildcardOrigins(value) {
  if (String(value ?? "").includes("*")) {
    throw new Error("Production ALLOWED_ORIGINS must not contain wildcards");
  }
}

function assertTrustedOrigins(value) {
  const entries = String(value ?? "")
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean);
  if (entries.length === 0) {
    throw new Error("Production BFF_TRUSTED_ORIGINS requires at least one browser origin");
  }
  for (const entry of entries) {
    let parsed;
    try {
      parsed = new URL(entry);
    } catch {
      throw new Error(`Production BFF_TRUSTED_ORIGINS contains invalid origin: ${entry}`);
    }
    if (parsed.origin !== entry.replace(/\/$/, "")) {
      throw new Error(`Production BFF_TRUSTED_ORIGINS must contain origins only: ${entry}`);
    }
    if (parsed.protocol !== "https:") {
      throw new Error(`Production BFF_TRUSTED_ORIGINS must use https:// origins: ${entry}`);
    }
    if (/(localhost|127\.0\.0\.1|10\.0\.2\.2)/i.test(parsed.hostname)) {
      throw new Error(`Production BFF_TRUSTED_ORIGINS must not point at localhost: ${entry}`);
    }
  }
}

function assertNoDevBypassInProtectedEnv(env) {
  if (String(env.DEV_BYPASS_ENABLED ?? "").trim().toLowerCase() === "true") {
    throw new Error("Production env must not enable DEV_BYPASS_ENABLED");
  }
  if (String(env.DEV_BYPASS_CREDENTIALS ?? "").trim()) {
    throw new Error("Production env must not configure DEV_BYPASS_CREDENTIALS");
  }
}

function assertCsrfGuardEnforcedInProtectedEnv(env) {
  if (String(env.BFF_CSRF_GUARD_MODE ?? "").trim().toLowerCase() === "dry-run") {
    throw new Error("Production env must set BFF_CSRF_GUARD_MODE=enforce");
  }
}

function assertCookieTtlMatchesAccessToken(env) {
  const accessMinutes = Number.parseInt(String(env.ACCESS_TOKEN_EXPIRE_MINUTES ?? ""), 10);
  const cookieMaxAge = Number.parseInt(String(env.COOKIE_MAX_AGE ?? ""), 10);
  if (!Number.isFinite(accessMinutes) || !Number.isFinite(cookieMaxAge)) return;
  const accessSeconds = accessMinutes * 60;
  if (cookieMaxAge > accessSeconds) {
    throw new Error("Production COOKIE_MAX_AGE must not exceed ACCESS_TOKEN_EXPIRE_MINUTES");
  }
}

function assertAndroidPackageName(value) {
  if (!ANDROID_PACKAGE_RE.test(String(value ?? "").trim())) {
    throw new Error("Production ANDROID_APP_LINK_PACKAGE_NAME must be a valid Android package name");
  }
}

function assertAndroidSha256Fingerprints(value) {
  const entries = String(value ?? "")
    .split(/[\s,]+/)
    .map((entry) => entry.trim().toUpperCase())
    .filter(Boolean);
  if (entries.length === 0) {
    throw new Error("Production ANDROID_APP_LINK_SHA256_CERT_FINGERPRINTS requires at least one SHA-256 fingerprint");
  }
  for (const entry of entries) {
    if (!ANDROID_SHA256_FINGERPRINT_RE.test(entry)) {
      throw new Error("Production ANDROID_APP_LINK_SHA256_CERT_FINGERPRINTS contains an invalid SHA-256 fingerprint");
    }
  }
}

function normalizeRedirectUri(value) {
  const parsed = new URL(String(value ?? "").trim());
  parsed.search = "";
  parsed.hash = "";
  return parsed.toString();
}

function assertMobileOAuthRedirectAllowlist(env) {
  const appLinkRedirect = normalizeRedirectUri(env.EXPO_PUBLIC_MOBILE_OAUTH_REDIRECT_URI);
  const allowed = String(env.MOBILE_OAUTH_REDIRECT_URIS ?? "")
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((entry) => normalizeRedirectUri(entry));
  if (!allowed.includes(appLinkRedirect)) {
    throw new Error("Production MOBILE_OAUTH_REDIRECT_URIS must include EXPO_PUBLIC_MOBILE_OAUTH_REDIRECT_URI");
  }
}

function assertHttps(env, key) {
  const value = String(env[key] ?? "");
  if (!value.startsWith("https://")) {
    throw new Error(`Production env key ${key} must use https://`);
  }
}

function assertWss(env, key) {
  const value = String(env[key] ?? "");
  if (!value.startsWith("wss://")) {
    throw new Error(`Production env key ${key} must use wss://`);
  }
}

export function renderTargetContent(env, targetName) {
  const target = TARGETS[targetName];
  if (!target) throw new Error(`Unknown target "${targetName}"`);
  const effectiveEnv = applyEnvDefaults(env);
  const lines = [...GENERATED_HEADER];
  for (const [sectionName, keys] of target.sections) {
    lines.push(`# ${sectionName}`);
    for (const key of keys) {
      lines.push(`${key}=${stringifyEnvValue(getRenderedEnvValue(effectiveEnv, targetName, key))}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function getRenderedEnvValue(env, targetName, key) {
  const value = env[key] ?? "";
  if (
    targetName === "mobile"
    && !isProtectedEnv(env)
    && normalizeUrlLikeValue(value) === LOCAL_MOBILE_EMULATOR_DEFAULTS.get(key)
  ) {
    return "";
  }
  return value;
}

function normalizeUrlLikeValue(value) {
  const text = String(value ?? "").trim();
  if (!text) return "";
  try {
    return new URL(text).toString().replace(/\/+$/, "");
  } catch {
    return text.replace(/\/+$/, "");
  }
}

export function renderTargets(env, targetNames, rootDir = DEFAULT_ROOT) {
  return targetNames.map((name) => ({
    name,
    absolutePath: path.join(rootDir, TARGETS[name].path),
    relativePath: TARGETS[name].path,
    content: renderTargetContent(env, name),
  }));
}

export function writeRenderedFile(file) {
  fs.mkdirSync(path.dirname(file.absolutePath), { recursive: true });
  const tempPath = path.join(path.dirname(file.absolutePath), `.${path.basename(file.absolutePath)}.${process.pid}.tmp`);
  fs.writeFileSync(tempPath, file.content, "utf8");
  fs.renameSync(tempPath, file.absolutePath);
}

function checkRenderedFile(file) {
  if (!fs.existsSync(file.absolutePath)) {
    return { ok: false, reason: "missing" };
  }
  const current = fs.readFileSync(file.absolutePath, "utf8");
  if (current !== file.content) {
    return { ok: false, reason: "stale" };
  }
  return { ok: true, reason: "ok" };
}

function parseArgs(argv) {
  const args = {
    master: DEFAULT_MASTER,
    root: DEFAULT_ROOT,
    target: "all",
    check: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--check") {
      args.check = true;
    } else if (arg === "--master") {
      args.master = path.resolve(argv[++i]);
    } else if (arg === "--root") {
      args.root = path.resolve(argv[++i]);
    } else if (arg === "--target") {
      args.target = argv[++i];
    } else if (arg === "--help" || arg === "-h") {
      args.help = true;
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return args;
}

function printHelp() {
  console.log(`Usage:
  node infra/scripts/render-env.mjs [--master infra/env/.env.master] [--target all|dev|prod|workers|backend|frontend|ai-worker|queue-worker|notification|compose-dev|compose-prod|mobile] [--check]

Examples:
  node infra/scripts/render-env.mjs --master infra/env/.env.master --target all
  node infra/scripts/render-env.mjs --target prod --check`);
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    printHelp();
    return;
  }
  if (!fs.existsSync(args.master)) {
    throw new Error(`Master env file not found: ${args.master}`);
  }
  const targetNames = resolveTargetNames(args.target);
  const env = parseDotenv(fs.readFileSync(args.master, "utf8"));
  validateEnv(env, targetNames, { requireProdValidation: args.target === "prod" || args.target === "compose-prod" });
  const rendered = renderTargets(env, targetNames, args.root);

  if (args.check) {
    let hasMismatch = false;
    for (const file of rendered) {
      const result = checkRenderedFile(file);
      if (result.ok) {
        console.log(`[OK] ${file.relativePath}`);
      } else {
        hasMismatch = true;
        console.log(`[${result.reason.toUpperCase()}] ${file.relativePath}`);
      }
    }
    if (hasMismatch) {
      throw new Error("Generated env files are not in sync with the master env.");
    }
    console.log("Env files match the master env.");
    return;
  }

  for (const file of rendered) {
    writeRenderedFile(file);
    console.log(`[WROTE] ${file.relativePath}`);
  }
  console.log("Env render complete. Values were not printed.");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (error) {
    console.error(`[render-env] ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}
