#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = path.resolve(SCRIPT_DIR, "../..");
const DEFAULT_MASTER = path.join(DEFAULT_ROOT, "infra/env/.env.master");
const GENERATED_HEADER = [
  "# Generated by infra/scripts/render-env.mjs from infra/env/.env.master.",
  "# Do not edit this file directly; update the master env and rerun sync-env.",
  "",
];

const TARGETS = {
  backend: {
    path: "backend/.env",
    sections: [
      ["App", ["APP_ENV", "NODE_ENV", "DEBUG", "LOG_LEVEL", "LOG_FORMAT", "APP_URL"]],
      ["Database and Redis", ["DATABASE_URL", "REDIS_URL", "CELERY_BROKER_URL"]],
      [
        "Storage",
        [
          "STORAGE_ENDPOINT",
          "STORAGE_ACCESS_KEY",
          "STORAGE_SECRET_KEY",
          "STORAGE_BUCKET_MEALS",
          "STORAGE_BUCKET_DOCS",
          "STORAGE_USE_SSL",
        ],
      ],
      [
        "Security",
        [
          "SECRET_KEY",
          "ALGORITHM",
          "ACCESS_TOKEN_EXPIRE_MINUTES",
          "REFRESH_TOKEN_EXPIRE_DAYS",
          "AUTH_ISSUER",
          "AUTH_AUDIENCE",
          "FERNET_KEY",
          "ALLOWED_ORIGINS",
          "BFF_SHARED_SECRET",
          "BFF_EXCHANGE_ISSUER",
          "BFF_EXCHANGE_AUDIENCE",
          "BFF_EXCHANGE_MAX_AGE_SECONDS",
          "METRICS_TOKEN",
          "METRICS_ALLOW_LOCAL",
        ],
      ],
      ["Service URLs", ["AI_WORKER_URL"]],
      ["Email", ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "SMTP_FROM", "SMTP_USE_TLS"]],
    ],
  },
  frontend: {
    path: "frontend/.env.local",
    sections: [
      ["BFF server runtime", ["CORE_API_URL", "REDIS_URL", "TRUST_PROXY"]],
      [
        "Auth cookies and CSRF",
        [
          "COOKIE_NAME",
          "COOKIE_MAX_AGE",
          "COOKIE_SECURE",
          "REFRESH_COOKIE_NAME",
          "REFRESH_COOKIE_MAX_AGE",
          "BFF_TRUSTED_ORIGINS",
          "BFF_CSRF_GUARD_MODE",
        ],
      ],
      ["NextAuth", ["NEXTAUTH_URL", "NEXTAUTH_SECRET"]],
      [
        "OAuth",
        [
          "ALLOWED_DEV_ORIGINS",
          "GOOGLE_CLIENT_ID",
          "GOOGLE_CLIENT_SECRET",
          "OAUTH_GOOGLE_CALLBACK_URL",
          "OAUTH_GOOGLE_LINK_CALLBACK_URL",
          "GITHUB_CLIENT_ID",
          "GITHUB_CLIENT_SECRET",
          "OAUTH_GITHUB_CALLBACK_URL",
          "OAUTH_GITHUB_LINK_CALLBACK_URL",
          "BFF_SHARED_SECRET",
        ],
      ],
      [
        "Public browser env",
        [
          "NEXT_PUBLIC_APP_URL",
          "NEXT_PUBLIC_CORE_WS_URL",
          "NEXT_PUBLIC_APP_ENV",
          "NEXT_PUBLIC_ONBOARDING_DRAFT_SERVER",
        ],
      ],
      ["Feature flags", ["ADMIN_SECURITY_FEED_ENABLED", "ADMIN_AUDIT_FEED_ENABLED", "DEV_BYPASS_CREDENTIALS"]],
    ],
  },
  "ai-worker": {
    path: "services/ai-worker/.env",
    sections: [
      ["App", ["DEBUG", "LOG_LEVEL"]],
      ["Service URLs", ["REDIS_URL", "CORE_API_URL"]],
      [
        "Storage",
        [
          "STORAGE_ENDPOINT",
          "STORAGE_ACCESS_KEY",
          "STORAGE_SECRET_KEY",
          "STORAGE_BUCKET_MEALS",
          "STORAGE_USE_SSL",
        ],
      ],
      [
        "AI",
        [
          "AI_MODEL_PATH",
          "AI_CONFIDENCE_THRESHOLD",
          "AI_YOLO_TIMEOUT_SECONDS",
          "AI_MAX_IMAGE_SIZE_PX",
          "AI_YOLO_MODEL_PATH",
          "AI_YOLO_GDRIVE_FILE_ID",
          "AI_YOLO_MODEL_SHA256",
          "AI_CLASS_NAMES_PATH",
          "AI_REQUEST_TIMEOUT_SECONDS",
          "AI_ALLOWED_IMAGE_HOSTS",
          "AI_IMAGE_DOWNLOAD_TIMEOUT_SECONDS",
          "AI_BLOCK_PRIVATE_NETWORKS",
          "AI_PROXY_BASE_URL",
          "AI_PROXY_MODEL",
          "AI_PROXY_API_KEY",
          "AI_CHAT_MAX_TOKENS",
          "AI_CHAT_TEMPERATURE",
          "AI_CHAT_TIMEOUT_SECONDS",
          "AI_CHAT_STREAM_CHUNK_MIN_CHARS",
        ],
      ],
    ],
  },
  "queue-worker": {
    path: "services/queue-worker/.env",
    sections: [
      ["App", ["DEBUG", "LOG_LEVEL"]],
      ["Queues", ["REDIS_URL", "CELERY_BROKER_URL", "CELERY_RESULT_BACKEND"]],
      ["Service URLs", ["CORE_API_URL", "AI_WORKER_URL"]],
      [
        "Storage",
        [
          "STORAGE_ENDPOINT",
          "STORAGE_ACCESS_KEY",
          "STORAGE_SECRET_KEY",
          "STORAGE_BUCKET_MEALS",
          "STORAGE_USE_SSL",
        ],
      ],
    ],
  },
  notification: {
    path: "services/notification/.env",
    sections: [
      ["App", ["DEBUG", "LOG_LEVEL"]],
      ["Service URLs", ["CORE_API_URL"]],
      ["Email", ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "SMTP_FROM", "SMTP_USE_TLS"]],
      ["Firebase", ["FIREBASE_PROJECT_ID", "FIREBASE_PRIVATE_KEY", "FIREBASE_CLIENT_EMAIL"]],
    ],
  },
  "compose-dev": {
    path: "infra/docker/.env.dev",
    sections: [
      [
        "Docker Compose dev substitution values",
        [
          "POSTGRES_DB",
          "POSTGRES_USER",
          "POSTGRES_PASSWORD",
          "REDIS_PASSWORD",
          "MINIO_ROOT_USER",
          "MINIO_ROOT_PASSWORD",
          "NEXTAUTH_SECRET",
          "BFF_SHARED_SECRET",
          "AI_WORKER_URL",
        ],
      ],
    ],
  },
  "compose-prod": {
    path: "infra/docker/.env.prod",
    sections: [
      [
        "Docker Compose production substitution values",
        [
          "POSTGRES_DB",
          "POSTGRES_USER",
          "POSTGRES_PASSWORD",
          "REDIS_PASSWORD",
          "MINIO_ROOT_USER",
          "MINIO_ROOT_PASSWORD",
          "STORAGE_ENDPOINT",
          "NEXTAUTH_URL",
          "NEXTAUTH_SECRET",
          "NEXT_PUBLIC_CORE_WS_URL",
          "BFF_SHARED_SECRET",
          "METRICS_TOKEN",
        ],
      ],
    ],
  },
  mobile: {
    path: "mobile/.env",
    sections: [["Expo public build-time env", ["EXPO_PUBLIC_CORE_API_URL", "EXPO_PUBLIC_CORE_WS_URL"]]],
  },
};

const TARGET_ALIASES = {
  all: Object.keys(TARGETS),
  dev: ["backend", "frontend", "ai-worker", "queue-worker", "notification", "compose-dev", "mobile"],
  prod: ["backend", "frontend", "ai-worker", "queue-worker", "notification", "compose-prod", "mobile"],
  workers: ["ai-worker", "queue-worker", "notification"],
};

const SECRET_KEY_PATTERN = /(SECRET|PASSWORD|TOKEN|PRIVATE|FERNET|API_KEY|CLIENT_SECRET|ACCESS_KEY)/i;
const PLACEHOLDER_PATTERN = /(change-me|replace-with|your-domain|example\.com|dev-secret|dev-bff-secret|dev-nextauth|healthos_dev_pass|minioadmin)/i;

export function parseDotenv(text) {
  const env = {};
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/);
  for (const [index, originalLine] of lines.entries()) {
    const line = originalLine.trim();
    if (!line || line.startsWith("#")) continue;
    const match = line.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match) {
      throw new Error(`Invalid env line ${index + 1}: ${originalLine}`);
    }
    env[match[1]] = parseValue(match[2]);
  }
  return env;
}

function parseValue(rawValue) {
  let value = rawValue.trim();
  if (!value) return "";
  const quote = value[0];
  if ((quote === '"' || quote === "'") && value.endsWith(quote)) {
    value = value.slice(1, -1);
    if (quote === '"') {
      value = value.replace(/\\n/g, "\n").replace(/\\r/g, "\r").replace(/\\t/g, "\t").replace(/\\"/g, '"').replace(/\\\\/g, "\\");
    }
    return value;
  }
  const commentIndex = findInlineComment(value);
  if (commentIndex !== -1) value = value.slice(0, commentIndex).trimEnd();
  return value;
}

function findInlineComment(value) {
  for (let index = 0; index < value.length; index += 1) {
    if (value[index] === "#" && (index === 0 || /\s/.test(value[index - 1]))) {
      return index;
    }
  }
  return -1;
}

export function stringifyEnvValue(value) {
  const text = String(value ?? "");
  if (text === "") return "";
  if ((text.startsWith("[") && text.endsWith("]")) || (text.startsWith("{") && text.endsWith("}"))) return text;
  if (/[\r\n]/.test(text)) return JSON.stringify(text);
  if (/^\s|\s$|[\s#"'`$\\]/.test(text)) return JSON.stringify(text);
  return text;
}

export function resolveTargetNames(target) {
  const requested = target || "all";
  const names = TARGET_ALIASES[requested] ?? [requested];
  for (const name of names) {
    if (!TARGETS[name]) {
      throw new Error(`Unknown target "${name}". Valid targets: ${Object.keys(TARGETS).join(", ")}, all, dev, prod, workers`);
    }
  }
  return names;
}

export function collectTargetKeys(targetNames) {
  const keys = new Set();
  for (const name of targetNames) {
    for (const [, sectionKeys] of TARGETS[name].sections) {
      for (const key of sectionKeys) keys.add(key);
    }
  }
  return [...keys].sort();
}

export function validateEnv(env, targetNames, options = {}) {
  const requiredKeys = collectTargetKeys(targetNames);
  const missing = requiredKeys.filter((key) => !(key in env));
  if (missing.length > 0) {
    throw new Error(`Master env is missing required key(s): ${missing.join(", ")}`);
  }

  for (const key of requiredKeys) assertPublicKeyIsSafe(key);

  const runtime = String(env.APP_ENV || env.NODE_ENV || "").trim().toLowerCase();
  const requireProd = options.requireProdValidation || runtime === "production" || runtime === "staging";
  if (!requireProd) return;

  const prodRequired = [
    "SECRET_KEY",
    "BFF_SHARED_SECRET",
    "DATABASE_URL",
    "REDIS_URL",
    "ALLOWED_ORIGINS",
    "STORAGE_ACCESS_KEY",
    "STORAGE_SECRET_KEY",
    "GOOGLE_CLIENT_SECRET",
    "GITHUB_CLIENT_SECRET",
    "FERNET_KEY",
    "METRICS_TOKEN",
    "NEXTAUTH_URL",
    "NEXTAUTH_SECRET",
    "POSTGRES_PASSWORD",
    "REDIS_PASSWORD",
    "MINIO_ROOT_USER",
    "MINIO_ROOT_PASSWORD",
    "NEXT_PUBLIC_APP_URL",
    "NEXT_PUBLIC_CORE_WS_URL",
    "EXPO_PUBLIC_CORE_API_URL",
    "EXPO_PUBLIC_CORE_WS_URL",
  ];
  for (const key of prodRequired) {
    assertPresent(env, key);
    assertNotPlaceholder(env, key);
  }

  assertMinLength(env, "SECRET_KEY", 32);
  assertMinLength(env, "BFF_SHARED_SECRET", 32);
  assertMinLength(env, "METRICS_TOKEN", 16);
  assertMinLength(env, "NEXTAUTH_SECRET", 32);
  assertNoLocalhost(env, "DATABASE_URL");
  assertNoLocalhost(env, "REDIS_URL");
  assertNoLocalhost(env, "ALLOWED_ORIGINS");
  assertNoWildcardOrigins(env.ALLOWED_ORIGINS);
  assertHttps(env, "NEXTAUTH_URL");
  assertHttps(env, "NEXT_PUBLIC_APP_URL");
  assertHttps(env, "EXPO_PUBLIC_CORE_API_URL");
  assertWss(env, "NEXT_PUBLIC_CORE_WS_URL");
  assertWss(env, "EXPO_PUBLIC_CORE_WS_URL");
}

export function assertPublicKeyIsSafe(key) {
  if ((key.startsWith("NEXT_PUBLIC_") || key.startsWith("EXPO_PUBLIC_")) && SECRET_KEY_PATTERN.test(key)) {
    throw new Error(`Public env key "${key}" looks secret-like. Server-only secrets must not use public prefixes.`);
  }
}

function assertPresent(env, key) {
  if (!String(env[key] ?? "").trim()) {
    throw new Error(`Production env requires non-empty ${key}`);
  }
}

function assertNotPlaceholder(env, key) {
  const value = String(env[key] ?? "");
  if (PLACEHOLDER_PATTERN.test(value)) {
    throw new Error(`Production env key ${key} still contains a placeholder/development value`);
  }
}

function assertMinLength(env, key, min) {
  if (String(env[key] ?? "").trim().length < min) {
    throw new Error(`Production env key ${key} must be at least ${min} characters`);
  }
}

function assertNoLocalhost(env, key) {
  const value = String(env[key] ?? "").toLowerCase();
  if (/(localhost|127\.0\.0\.1|10\.0\.2\.2)/.test(value)) {
    throw new Error(`Production env key ${key} must not point at localhost/emulator addresses`);
  }
}

function assertNoWildcardOrigins(value) {
  if (String(value ?? "").includes("*")) {
    throw new Error("Production ALLOWED_ORIGINS must not contain wildcards");
  }
}

function assertHttps(env, key) {
  const value = String(env[key] ?? "");
  if (!value.startsWith("https://")) {
    throw new Error(`Production env key ${key} must use https://`);
  }
}

function assertWss(env, key) {
  const value = String(env[key] ?? "");
  if (!value.startsWith("wss://")) {
    throw new Error(`Production env key ${key} must use wss://`);
  }
}

export function renderTargetContent(env, targetName) {
  const target = TARGETS[targetName];
  if (!target) throw new Error(`Unknown target "${targetName}"`);
  const lines = [...GENERATED_HEADER];
  for (const [sectionName, keys] of target.sections) {
    lines.push(`# ${sectionName}`);
    for (const key of keys) {
      lines.push(`${key}=${stringifyEnvValue(env[key] ?? "")}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export function renderTargets(env, targetNames, rootDir = DEFAULT_ROOT) {
  return targetNames.map((name) => ({
    name,
    absolutePath: path.join(rootDir, TARGETS[name].path),
    relativePath: TARGETS[name].path,
    content: renderTargetContent(env, name),
  }));
}

export function writeRenderedFile(file) {
  fs.mkdirSync(path.dirname(file.absolutePath), { recursive: true });
  const tempPath = path.join(path.dirname(file.absolutePath), `.${path.basename(file.absolutePath)}.${process.pid}.tmp`);
  fs.writeFileSync(tempPath, file.content, "utf8");
  fs.renameSync(tempPath, file.absolutePath);
}

function checkRenderedFile(file) {
  if (!fs.existsSync(file.absolutePath)) {
    return { ok: false, reason: "missing" };
  }
  const current = fs.readFileSync(file.absolutePath, "utf8");
  if (current !== file.content) {
    return { ok: false, reason: "stale" };
  }
  return { ok: true, reason: "ok" };
}

function parseArgs(argv) {
  const args = {
    master: DEFAULT_MASTER,
    root: DEFAULT_ROOT,
    target: "all",
    check: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--check") {
      args.check = true;
    } else if (arg === "--master") {
      args.master = path.resolve(argv[++i]);
    } else if (arg === "--root") {
      args.root = path.resolve(argv[++i]);
    } else if (arg === "--target") {
      args.target = argv[++i];
    } else if (arg === "--help" || arg === "-h") {
      args.help = true;
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return args;
}

function printHelp() {
  console.log(`Usage:
  node infra/scripts/render-env.mjs [--master infra/env/.env.master] [--target all|dev|prod|workers|backend|frontend|ai-worker|queue-worker|notification|compose-dev|compose-prod|mobile] [--check]

Examples:
  node infra/scripts/render-env.mjs --master infra/env/.env.master --target all
  node infra/scripts/render-env.mjs --target prod --check`);
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    printHelp();
    return;
  }
  if (!fs.existsSync(args.master)) {
    throw new Error(`Master env file not found: ${args.master}`);
  }
  const targetNames = resolveTargetNames(args.target);
  const env = parseDotenv(fs.readFileSync(args.master, "utf8"));
  validateEnv(env, targetNames, { requireProdValidation: args.target === "prod" || args.target === "compose-prod" });
  const rendered = renderTargets(env, targetNames, args.root);

  if (args.check) {
    let hasMismatch = false;
    for (const file of rendered) {
      const result = checkRenderedFile(file);
      if (result.ok) {
        console.log(`[OK] ${file.relativePath}`);
      } else {
        hasMismatch = true;
        console.log(`[${result.reason.toUpperCase()}] ${file.relativePath}`);
      }
    }
    if (hasMismatch) {
      throw new Error("Generated env files are not in sync with the master env.");
    }
    console.log("Env files match the master env.");
    return;
  }

  for (const file of rendered) {
    writeRenderedFile(file);
    console.log(`[WROTE] ${file.relativePath}`);
  }
  console.log("Env render complete. Values were not printed.");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (error) {
    console.error(`[render-env] ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}
