"""Emergency access logs — preserve audit trail across token + user purges.

Revision ID: 027_emergency_access_log_fk_fix
Revises: 026_emergency_profile_share
Create Date: 2026-04-19

F4 (review fix) — the original migration 026 declared:

  * `emergency_access_logs.token_id` FK with `ON DELETE CASCADE`
  * `emergency_access_logs.user_id`  FK with `ON DELETE SET NULL`

These two policies contradict each other: when a user is purged the user
cascade drops their tokens, the token cascade then drops every access log,
and the `user_id SET NULL` is unreachable. Either:

  (a) keep cascade-only and the audit history vanishes at purge — or
  (b) drop the token cascade so logs survive both token-revocation +
      user-purge with `user_id` set to NULL after purge.

We chose (b) — emergency-card audit history is genuinely useful for the
support team to forensically investigate "my card was scraped 9k times,
where from?" reports even after the user has revoked the token. The user
purge still anonymizes the row (user_id → NULL) so PHI exposure is bounded.

Concretely this migration:
  1. Drops the existing FK with CASCADE on `token_id`.
  2. Re-creates it with SET NULL.
  3. Makes `token_id` nullable (required for SET NULL to be effective).

Downgrade reverses both changes — but rows whose token has been deleted
in the meantime will lose their `token_id` reference and cannot be
re-attached.
"""
from __future__ import annotations

from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

revision: str = "027_emergency_access_log_fk_fix"
down_revision: Union[str, None] = "026_emergency_profile_share"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Drop the existing CASCADE FK on token_id. The constraint name is
    #    auto-generated by Postgres in 026 (we did not name it). Use the
    #    information_schema lookup to find it portably.
    op.execute(
        """
        DO $$
        DECLARE
            cname text;
        BEGIN
            SELECT tc.constraint_name INTO cname
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema   = kcu.table_schema
            WHERE tc.table_name = 'emergency_access_logs'
              AND tc.constraint_type = 'FOREIGN KEY'
              AND kcu.column_name = 'token_id'
            LIMIT 1;
            IF cname IS NOT NULL THEN
                EXECUTE format('ALTER TABLE emergency_access_logs DROP CONSTRAINT %I', cname);
            END IF;
        END
        $$;
        """
    )

    # 2. Make token_id nullable so the SET NULL policy is meaningful.
    op.alter_column(
        "emergency_access_logs",
        "token_id",
        existing_type=UUID(as_uuid=True),
        nullable=True,
    )

    # 3. Re-create the FK with SET NULL.
    op.create_foreign_key(
        "fk_emergency_access_logs_token_id",
        "emergency_access_logs",
        "emergency_share_tokens",
        ["token_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # Drop SET NULL FK.
    op.drop_constraint(
        "fk_emergency_access_logs_token_id",
        "emergency_access_logs",
        type_="foreignkey",
    )

    # NOTE: any rows whose token_id is already NULL (because the original
    # token row was deleted while this migration was applied) will fail
    # the NOT NULL constraint below. The `WHERE` clause keeps the down
    # migration idempotent in mixed-state envs by deleting orphaned rows
    # first — they no longer carry a referenceable identity anyway.
    op.execute(
        "DELETE FROM emergency_access_logs WHERE token_id IS NULL"
    )

    op.alter_column(
        "emergency_access_logs",
        "token_id",
        existing_type=UUID(as_uuid=True),
        nullable=False,
    )

    op.create_foreign_key(
        None,
        "emergency_access_logs",
        "emergency_share_tokens",
        ["token_id"],
        ["id"],
        ondelete="CASCADE",
    )
