export const ROUTES = {
  // Tabs
  home:  '/home',
  care:  '/care',
  chat:  '/chat',
  meds:  '/meds',
  me:    '/me',
  // Auth
  authWelcome:  '/auth/welcome',
  authSignIn:   '/auth/sign-in',
  authSignUp:   '/auth/sign-up',
  authOtp:      '/auth/otp',
  authSetup:    '/auth/setup',
  authMfa:      '/auth/mfa',
  authForgot:   '/auth/forgot',
  // Home
  homeToday:    '/home/today',
  homeScore:    '/home/score',
  homeVitals:   '/home/vitals',
  homeQuickAction: '/home/quick-action',
  // Care
  careAppointments:    '/care/appointments',
  careAppointmentsNew: '/care/appointments/new',
  careHistory:         '/care/history',
  carePrescriptions:   '/care/prescriptions',
  careAttachments:     '/care/attachments',
  careLabReports:      '/care/lab-reports',
  // Meds
  medsAdd:     '/meds/add',
  medsHistory: '/meds/history',
  medsImport:  '/meds/import',
  medsTakeSample:   '/meds/test-id/take',
  medsMissedSample: '/meds/test-id/missed',
  // Profile
  profileHealth:   '/profile/health',
  profileDevices:  '/profile/devices',
  profileSecurity: '/profile/security',
  // Insights
  insights:          '/insights',
  insightsGoals:     '/insights/goals',
  insightsMilestones: '/insights/goals/milestones',
  // Reminders
  reminders: '/reminders',
} as const;
